### ISSUE TITLE
Layer-by-layer spike propagation

### ISSUE THREAD

**Issue by bjourne** [putshua/ANN_SNN_QCFS#9]
Thanks for making the source code of your research available - it greatly improves understanding.

In the source for the IF neuron in `layer.py` the neuron is simulated for `T` time steps before its output is forwarded to the next layer. Thus, the latency for every IF layer is `T` time steps. And since there are about 15 IF layers in VGG16, doesn't that mean that the total latency is `15*T`?

**Comment by putshua** [comment]
We implement this as layer-by-layer forward as it is more efficient on GPU. In fact, an equivalent depth-first implementation can be used in pratical.

**Comment by bjourne** [comment]
Ah, yes. You are right. I misunderstood the source. Memory usage is quite high though!
